esphome:
   name: kludges
   platform: ESP32
   board: lolin32

wifi:
  ssid: mkwadraat-iot
  password: !secret wifi_password

ota:

web_server:
  port: 80

sensor:
  - platform: adc
    name: "Rechts"
    pin: A3
    id: sensor_middle
    update_interval: 0.1s
    attenuation: 11db
  - platform: adc
    name: "Links"
    pin: A4
    id: sensor_right
    update_interval: 0.1s
    attenuation: 11db
  - platform: adc
    name: "Midden"
    pin: A5
    id: sensor_left
    update_interval: 0.1s
    attenuation: 11db

